# Generated by Django 5.0.7 on 2024-08-05 20:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.UUIDField(default=uuid.UUID('b8903187-b282-479e-948e-2500533dd0f2'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='catalog.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('c4187011-b276-4399-8ca5-c67a1dfdc1f8'), primary_key=True, serialize=False, unique=True),
        ),
    ]
