# Generated by Django 5.0.7 on 2024-08-05 20:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_author_author_id_alter_book_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="author_id",
            field=models.UUIDField(
                default=uuid.UUID("5e77f2ce-b303-4893-b359-220de1e2c559"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_id",
            field=models.UUIDField(
                default=uuid.UUID("6ee9283c-f0fe-49a2-aa9d-d0c57dd12d51"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
