# Generated by Django 5.0.7 on 2024-08-05 20:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_author_author_id_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.UUIDField(default=uuid.UUID('e1294b8d-95e1-487e-b1ad-356deb00ba63'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('7199bfbb-64e5-4e2f-9911-e716f6ad5994'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
