# Generated by Django 5.0.7 on 2024-08-06 19:49

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_author_author_id_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.UUIDField(default=uuid.UUID('c7db0162-0f26-4591-bb80-13bbdd34fcfa'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('d68c2fbc-602f-4ada-9a74-bd983263a66a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, help_text='введите год выпуска книги (при его наличии)', validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
