# Generated by Django 5.0.7 on 2024-08-10 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_author_author_id_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.UUIDField(default=uuid.UUID('51bb19c2-9ae5-423d-be66-52c10a562062'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('75fb9ee7-8610-448a-bfea-a85c14cd16a9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
