# Generated by Django 5.0.7 on 2024-08-11 17:01

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_author_author_id_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.UUIDField(default=uuid.UUID('1cc8ec5b-2c1a-4661-a142-1b0764387d2e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('72aa35e1-00ec-4769-ba55-3fb5997ab8ab'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_year',
            field=models.PositiveIntegerField(help_text='введите год выпуска книги (при его наличии)', validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
