# Generated by Django 5.0.7 on 2024-08-11 17:04

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_author_author_id_alter_book_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.UUIDField(default=uuid.UUID('7476a4fb-c703-49b0-b704-6baef9320383'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('243787cc-139d-4ca9-9a94-3c9c809eb3c6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_year',
            field=models.PositiveIntegerField(help_text='введите год выпуска книги (при его наличии)', null=True, validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='введите название книги', max_length=300, verbose_name='Название книги'),
        ),
    ]
