# Generated by Django 5.0.7 on 2024-08-11 17:10

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_author_author_id_alter_book_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about_author',
            field=models.TextField(blank=True, help_text='об авторе', max_length=2000, verbose_name='Об авторе'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.UUIDField(default=uuid.UUID('8a96c98c-ffdf-472e-88d3-ae7e0f2f901e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='введите автора', max_length=100, verbose_name='Фамилия Имя'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='catalog.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('24fb5bdd-6990-450b-b001-fe60a6aa6bec'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='введите описание книги', max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='укажите жанр(-ы) книги', to='catalog.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, help_text='введите год выпуска книги (при его наличии)', null=True, validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(2050)], verbose_name='Год издания'),
        ),
    ]
