# Generated by Django 5.0.7 on 2024-08-12 19:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_alter_author_author_id_alter_book_book_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="author_id",
            field=models.UUIDField(
                editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_id",
            field=models.UUIDField(
                default=uuid.UUID("1b16428d-703f-4c7e-b669-272ee5249fae"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
