# Generated by Django 5.0.7 on 2024-08-12 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_alter_author_author_id_alter_book_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="author_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_id",
            field=models.UUIDField(
                default=uuid.UUID("8e0c3f66-d066-4e1f-93fe-34de34d7df5a"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
