# Generated by Django 5.0.7 on 2024-08-12 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_alter_book_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="release_year",
            field=models.PositiveIntegerField(
                blank=True,
                default="не указан",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(800),
                    django.core.validators.MaxValueValidator(2050),
                ],
                verbose_name="Год издания",
            ),
        ),
    ]
