# Generated by Django 5.0.7 on 2024-08-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="moderator",
            field=models.BooleanField(
                default=False, verbose_name="обладает правами модератора"
            ),
        ),
    ]
